
spring:
  profiles:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/seulki
    username: root
    password: seulki345**


mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: kr.co.crewmate.carrot.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    kr.co.crewmate.carrot: DEBUG

diskPath:
  commonPath: "./src/main/resources/static"
  productPath: "/product/image"
  villagePath: "/village-post/image"
  questionPath: "/question/image"

resourceHandler:
  villagePost : "/villagePostImage/**"